---
- name: Configure sysctl
  tags: sysctl
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_dict: "{{ sysctl_config }}"

- name: Create banner base
  set_fact:
    BANNER_MOTD: "AS{{ ROUTERASN }} James Ledger"

- name: Add location if present
  set_fact:
    BANNER_MOTD: "{{ BANNER_MOTD }} {{ ROUTERLOCATION }}"
  when: ROUTERLOCATION is defined

- name: Set banner
  shell: "/bin/figlet -w 115 -c {{ BANNER_MOTD }} > /etc/motd"

- name: Ensure MOTD is enabled in sshd
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: "PrintMotd yes"
  notify: sshd_restart

- name: Ensure pam isn't printing MOTD
  lineinfile:
    path: /etc/pam.d/sshd
    state: absent
    line: "{{ item }}"
  loop:
    - "session    optional     pam_motd.so  motd=/run/motd.dynamic"
    - "session    optional     pam_motd.so noupdate"