- name: Create OSPF Links File
  tags: install,ospf
  file:
    path: /etc/bird/links.conf
    owner: bird
    group: bird
    mode: '0644'
    state: touch
    force: no

- name: Install OSPF Neighbors
  tags: install,ospf
  lineinfile:
    path: /etc/bird/links.conf
    line: 'interface "{{ item.key }}"   { type pointopoint; hello 12; dead 46; cost {{ item.value }}; bfd on; };'
  with_dict: "{{ ADJACENT_ROUTERS }}"
  notify: bird_reconfig
