- name: Copy Files
  tags: install
  copy:
    src: .
    dest: /etc/bird/
    owner: bird
    group: bird

- name: Configure variables.conf Template
  tags: configure
  template:
    src: "variables.conf"
    dest: /etc/bird/variables.conf
    owner: bird
    group: bird
  notify: bird_service

- name: Configure filters.conf Template
  tags: configure
  template:
    src: "filters.conf"
    dest: /etc/bird/filters.conf
    owner: bird
    group: bird
  notify: bird_service

- name: Configure templates.conf Template
  tags: configure
  template:
    src: "templates.conf"
    dest: /etc/bird/templates.conf
    owner: bird
    group: bird
  notify: bird_service

- name: Configure protocols.conf Template
  tags: configure
  template:
    src: "protocols.conf"
    dest: /etc/bird/protocols.conf
    owner: bird
    group: bird
  notify: bird_service

- name: Configure communities.conf Template
  tags: configure
  template:
    src: "communities.conf"
    dest: /etc/bird/communities.conf
    owner: bird
    group: bird
  notify: bird_service

- name: Configure bird.conf Template
  tags: configure
  template:
    src: "bird.conf"
    dest: /etc/bird/bird.conf
    owner: bird
    group: bird
  notify: bird_service

- name: Set Bird Permissions
  tags: install
  file:
    path: /etc/bird
    owner: bird
    group: bird
    recurse: yes