- name: Remove BIRD1
  apt:
    pkg: bird
    state: absent

- name: Install Packages
  tags: install
  apt:
    pkg:
    - curl
    - bird2
    - nload
    - net-tools
    - htop
    - rsync
    - mtr-tiny
    - vim
    - traceroute
    - figlet
