- name: Copy Files
  tags: install
  ansible.builtin.copy:
    src: .
    dest: /etc/bird/
    owner: bird
    group: bird
  
- name: Set Bird Permissions
  tags: install
  ansible.builtin.file:
    path: /etc/bird
    owner: bird
    group: bird
    recurse: yes

- name: Check if shared folder exists
  tags: install
  stat:
    path: /etc/bird/shared
  register: shared

- name: Create shared folder if not present
  tags: install
  file:
    state: directory
    path: /etc/bird/shared
    mode: 0755
  when: shared.stat.exists == false

- name: Configure shared/config.conf Template
  tags: configure
  template:
    src: "{{ SHARECONFIG }}"
    dest: /etc/bird/shared/config.conf
    owner: bird
    group: bird
  notify: bird_reconfig

- name: Configure shared/filters.conf Template
  tags: configure
  template:
    src: "{{ FILTERSCONFIG }}"
    dest: /etc/bird/shared/filters.conf
    owner: bird
    group: bird
  notify: bird_reconfig

- name: Configure shared/protocols.conf Template
  tags: configure
  template:
    src: "{{ PROTOCOLSCONFIG }}"
    dest: /etc/bird/shared/protocols.conf
    owner: bird
    group: bird
  notify: bird_reconfig

- name: Configure ./bird6.conf Template
  tags: configure
  template:
    src: "{{ BIRDCONFIG }}"
    dest: /etc/bird/bird6.conf
    owner: bird
    group: bird
  notify: bird_reconfig

- name: Check if peers folder is present
  tags: install
  stat:
    path: /etc/bird/ipv6/peers
  register: peers

- name: Create peers folder if it does not exist
  tags: install
  file:
    state: directory
    path: /etc/bird/ipv6/peers
    mode: 0755
  when: peers.stat.exists == false
  
- name: Configure ipv6/peers/transit.conf Template
  tags: configure
  template:
    src: "{{ TRANSITCONFIG }}"
    dest: /etc/bird/ipv6/peers/transit.conf
    owner: bird
    group: bird
  notify: bird_reconfig

- name: Configure ipv6/peers/static.conf Template
  tags: configure
  template:
    src: "{{ STATICCONFIG }}"
    dest: /etc/bird/ipv6/peers/static.conf
    owner: bird
    group: bird
  notify: bird_reconfig

- name: Configure ipv6/prefixes/mynet.conf Template
  tags: configure
  template:
    src: "{{ MYNETCONFIG }}"
    dest: /etc/bird/ipv6/prefixes/mynet.conf
    owner: bird
    group: bird
  notify: bird_reconfig

- name: Start BIRD6 Service
  service: 
    name: bird6
    state: restarted
    enabled: yes
  notify: bird_reconfig