---
- name: Remove Interfaces.d Reading From Start Of Interfaces
  tags: install
  lineinfile:
    regexp: "/^source /etc/network/interfaces.d/*$/"
    path: /etc/network/interfaces
    state: absent

- name: Insert Interfaces.d Reading At End Of Interfaces
  tags: install
  lineinfile:
    path: /etc/network/interfaces
    line: "source /etc/network/interfaces.d/*.conf"

- name: Install Loop Interface (interfaces.d)
  tags: install
  template:
    src: "bgp_interfaces.conf"
    dest: /etc/network/interfaces.d/bgp_interfaces.conf
    owner: root
    group: root
  notify: interfaces

#- name: Deploy GRE Tunnels
#  template:
#    src: "gre.conf"
#    dest: "/etc/network/interfaces.d/{{ item }}.conf"
#    owner: root
#    group: root
#  loop: "{{ lookup('inventory_hostnames', 'all', wantlist=True) }}"
#  loop_control:
#    extended: yes