- name: bird_reconfig
  tags: reconfig
  ansible.builtin.command:
    cmd: "birdc6 c"

- name: bird_service
  service: 
    name: bird6
    state: restarted
    enabled: yes
  notify: bird_reconfig

- name: interfaces
  tags: interfaces
  command:
    cmd: "ifup lo:{{ ANYCAST_LOOP }}"
  loop: "{{ ANYCAST_ADDRESS }}"
  loop_control:
    index_var: ANYCAST_LOOP

- name: sshd_restart
  service:
    name: sshd
    state: restarted
    enabled: yes
    
